In [3]:
import seaborn as sns
import pandas as pd

In [4]:
# def readPDB
# Team Member: Joseph Rocha
# Purpose: reads a pdb file into a list
# Parameters:
#            path - The path of the file to be read
# Returns: a list of lines
# Notes: The path parameter will be replaced with a link.
#        Open will be replaced by a URL request.

In [5]:
def readPDB(path):
    file = open(path, "r")
    lines = file.readlines()
    lines = [line.strip("\n") for line in lines]
    return lines

In [6]:
# def returnSection
# Team Member: Joseph Rocha
# Purpose: returns a list of lines that start with the given
# Parameters:
#            lines - lines to be
#            start - the string that the line should start with
# Returns: a list of lines that start with start.

In [7]:
def returnSection(lines, start):
    return [line for line in lines if line.startswith(start)]

In [8]:
#WARNING! Amino Acid 202 is missing in PDB, but we don't handle it here, should we skip???
def getSEQRESDf(seqres):
    df = pd.DataFrame(columns=['serNum', 'chainID', 'numRes', 'seqNum', 'residue'])
    for line in seqres:
        sequence = line[19:].split()
        for idx, residue in enumerate(sequence):
            serNum = line[7:11].strip() # COLUMNS 8 - 10, serNum
            chainID = line[11].strip() #COLUMNS 11, chainID
            numRes = line[13:17].strip() #COLUMNS, numRes
            seqNum = (idx+1)+((int(serNum)-1)*13)
            df = df.append({'serNum': serNum,
                            'chainID': chainID,
                            'numRes': numRes,
                            'seqNum': seqNum,
                            'residue': residue}, ignore_index=True)
    return df

In [9]:
def getBetaSheetDf(strands):
    df = pd.DataFrame(columns=['strand', 
                               'numStrands',
                               'initChainID',
                               'initSeqNum',
                               'endChainID',
                               'endSeqNum'])
    for line in strands:
        strand = line[7:10].strip()
        numStrands = line[14:16].strip()
        initChainID = line[21].strip()
        initSeqNum = line[22:26].strip()
        endChainID = line[32].strip()
        endSeqNum = line[33:37].strip()
        df = df.append({'strand': strand,
                        'numStrands': numStrands,
                        'initChainID': initChainID,
                        'initSeqNum': initSeqNum,
                        'endChainID': endChainID,
                        'endSeqNum': endSeqNum}, ignore_index=True)
    return df

In [25]:
def getHelixDf(strands):
    df = pd.DataFrame(columns=['serNum', 
                               'initChainID',
                               'initSeqNum',
                               'endChainID',
                               'endSeqNum',
                               'helixClass',
                               'length'])
    for line in strands:
        serNum = line[7:10].strip()
        initChainID = line[19].strip()
        initSeqNum = line[21:25].strip()
        endChainID = line[31].strip()
        endSeqNum = line[33:37].strip()
        helixClass = line[38:40].strip()
        length = line[71:76].strip()
        df = df.append({'serNum': serNum,
                        'initChainID': initChainID,
                        'initSeqNum': initSeqNum,
                        'endChainID': endChainID,
                        'endSeqNum': endSeqNum,
                        'helixClass': helixClass,
                        'length': length}, ignore_index=True)
    return df

In [26]:
lines = readPDB("3uts.pdb")
helix = returnSection(lines, "HELIX")
helix_df = getHelixDf(helix)
helix_df.head()

  serNum initChainID initSeqNum endChainID endSeqNum helixClass length
0      1           A         49          A        54          1      6
1      2           A         56          A        85          1     30
2      3           A        137          A       150          1     14
3      4           A        151          A       162          1     12
4      5           A        162          A       175          1     14

In [15]:
sheets = returnSection(lines, "SHEET")
sheets_df = getBetaSheetDf(sheets)
sheets_df.head()

  strand numStrands initChainID initSeqNum endChainID endSeqNum
0      1          8           A         46          A        47
1      2          8           A         31          A        37
2      3          8           A         21          A        28
3      4          8           A          3          A        12
4      5          8           A         94          A       103

In [16]:
seqres = returnSection(lines, "SEQRES")
seqres_df = getSEQRESDf(seqres)
seqres_df.head()

  serNum chainID numRes seqNum residue
0      1       A    276      1     GLY
1      1       A    276      2     SER
2      1       A    276      3     HIS
3      1       A    276      4     SER
4      1       A    276      5     MET